updating build image

diff --git a/.github/workflows/createImage.yml b/.github/workflows/createImage.yml
--- a/.github/workflows/createImage.yml
+++ b/.github/workflows/createImage.yml
@@ -142,6 +142,46 @@ jobs:
       # 2. Fetch the latest AMI ID from Packer Build
       - name: Fetch Latest AMI ID
         run: |
-          ami_id=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d':' -f2)
-          echo "AMI_ID=$ami_id" >> $GITHUB_ENV          
+          # Check if manifest.json exists before processing
+          if [ -f ./packer/manifest.json ]; then
+            ami_id=$(jq -r '.builds[-1].artifact_id' ./packer/manifest.json | cut -d':' -f2)
+            echo "AMI_ID=$ami_id" >> $GITHUB_ENV
+          else
+            echo "manifest.json not found!"
+            exit 1
+          fi
+
+      # 3. Update the Launch Template with the new AMI
+      - name: Update Launch Template
+        run: |
+          aws ec2 create-launch-template-version \
+            --launch-template-name ${{ env.LAUNCH_TEMPLATE_NAME }} \
+            --version-description "WebVersion2" \
+            --source-version 1 \
+            --launch-template-data '{"ImageId":"${{ env.AMI_ID }}"}'
+
+      # 4. Trigger instance refresh on Auto Scaling Group
+      - name: Trigger Instance Refresh
+        run: |
+          aws autoscaling start-instance-refresh \
+            --auto-scaling-group-name ${{ env.AUTO_SCALING_GROUP_NAME }}
+          
+      # 5. Wait for the instance refresh to complete
+      - name: Wait for Instance Refresh to Complete
+        run: |
+          status=$(aws autoscaling describe-instance-refreshes \
+            --auto-scaling-group-name ${{ env.AUTO_SCALING_GROUP_NAME }} \
+            --query 'InstanceRefreshes[0].Status' \
+            --output text)
+          while [[ "$status" != "Successful" && "$status" != "Failed" && "$status" != "Cancelled" ]]; do
+            sleep 60
+            status=$(aws autoscaling describe-instance-refreshes \
+              --auto-scaling-group-name ${{ env.AUTO_SCALING_GROUP_NAME }} \
+              --query 'InstanceRefreshes[0].Status' \
+              --output text)
+          done
+
+          if [ "$status" == "Failed" ] || [ "$status" == "Cancelled" ]; then
+            exit 1
+          fi       
 
